### ISSUE TITLE
Security risk of putting undo tree log in the same folder

### ISSUE THREAD

**Issue by lanyusan** [MatthewZMD/.emacs.d#52]
I noticed the latest version has the undo tree log in the same folder of the file being edited.

The log file could be added to git repo easily with `git add -A`. Sometimes it could potentially include sensitive information that user thought it had been deleted but would be stilled included in the undo tree as edit log.

I strongly advise to REMOVE this feature. 

At least it is a huge concern for me, as I use your configure as main config and I use it to edit code or config files that would be used in production servers. I might add secret temporarily for local testing and then delete it before deployment. It could easily be leaked by this feature.

This is VERY dangerous.

**Comment by MatthewZMD** [comment]
I completely agree with you regarding a recent change with undotree, I see no reason of putting undo tree log in the same folder as well.

I went to read their change log and discovered `undo-tree-history-directory-alist`, that's why I pushed d740894e3d4bcaed8c679b404c901d0067fe3d19 to store the undo tree logs in your Emacs backup directory. It works on my system, does it not work on yours too?

**Comment by lanyusan** [comment]
I hadn't synced with your latest when I wrote the issue. I pulled the latest of yours. It seems to have fixed the problem.

Thanks.

**Comment by MatthewZMD** [comment]
This is great to hear! Closing the issue now.
